---

- name: 'create certs directory'
  file:
    path: "{{ _nomad_certs_dir }}"
    owner: 'root'
    group: "{{ _nomad_group }}"
    mode: '0750'
    state: 'directory'

- name: 'create certs'
  copy:
    content: "{{ item.content }}"
    dest: "{{ _nomad_certs_dir }}/{{ item.name }}"
    owner: 'root'
    group: "{{ _nomad_group }}"
    mode: '0640'
  loop: "{{ nomad_config_tls_files }}"
  notify:
    - 'nomad_restart_handler'

- name: 'create main nomad conf file'
  template:
    src: 'etc/nomad/nomad.hcl.j2'
    dest: "{{ _nomad_conf_dir }}/nomad.hcl"
    owner: 'root'
    group: "{{ _nomad_group }}"
    mode: '0640'
  notify:
    - 'nomad_restart_handler'
