---

- name: 'create directories'
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: 'directory'
  loop:
    - path: "{{ _nomad_conf_dir }}"
      owner: 'root'
      group: "{{ _nomad_group }}"
      mode: "0750"

    - path: "{{ _nomad_data_dir }}"
      owner: "{{ _nomad_user }}"
      group: "{{ _nomad_group }}"
      mode: "0750"
